2DUNet:
  model: 'UNet'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]

3DUNet:
  model: 'UNet'
  network:
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]

2DResUNet:
  model: 'UNet'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]
    num_res_units: 1

ResNet50UNet:
  model: 'ResNet50UNet'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]
    num_res_units: 1

3DResUNet:
  model: 'UNet'
  network:
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]
    num_res_units: 1

2DAttentionUnet:
  model: 'AttentionUnet'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]

3DAttentionUnet:
  model: 'AttentionUnet'
  network:
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    channels: [16, 32, 64, 128, 128, 256]
    strides: [2, 2, 2, 2, 2]

2DUNETR:
  model: 'UNETR'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    img_size: [384, 384]

3DUNETR:
  model: 'UNETR'
  network:
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    img_size: [128, 128, 128]

2DSwinUNETR:
  model: 'SwinUNETR'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    img_size: [384, 384]

3DSwinUNETR:
  model: 'SwinUNETR'
  network:
    spatial_dims: 2
    in_channels: 1
    out_channels: 2
    img_size: [128, 128, 128]

