network_structure:
  model_name: '2DAttentionUnet'
  model_config:
    loss: 'DiceCELoss'
    in_channels: 1
    out_channels: 2

dataset:
  path_dir: '/data/datasets/DiffusionMedAug/spleen/processed/2DSliceEdge'
  fold: 1
  transform: null
  batch_size: 8
  patch_size: [384, 384]
  data_type: '3D'
  augment_ratio: 10

evaluation:
  _lab2cname:
    0: 'background'
    1: 'spleen'
  extra_name: ''

training_setting:
  epoch: 100
  model_dir: './models/spleen.ckpt'
  result_dir: './results/spleen'
